kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sample-pvc
  annotations:
    volume.kubernetes.io/storage-class: "nfs"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi
